### ISSUE TITLE
XSS  Stealing cookies

### ISSUE THREAD

**Issue by shangzeng** [Cherry-toto/jizhicms#16]
JIZHICMS 1.5.1 allows XSS to add an administrator cookie.

New normal account  =>  New articles
![1584327644773](https://user-images.githubusercontent.com/56285852/76719830-f22b9b00-6775-11ea-9502-0cb2149d989e.jpg)

code:

```
<script>alert(1)</script>
```
![1584327682117](https://user-images.githubusercontent.com/56285852/76720030-97467380-6776-11ea-8a6e-b3bab76239d6.jpg)

Go to administrator background

![1584327730818](https://user-images.githubusercontent.com/56285852/76719894-24d59380-6776-11ea-9621-93de6f25bf1f.jpg)

Click on the title to trigger XSS

![1584327796413](https://user-images.githubusercontent.com/56285852/76719978-67976b80-6776-11ea-9dff-15dec827d284.jpg)

**Comment by Cherry-toto** [comment]
yes，You're right ！
The bug was solve in version 1.6.3+ ，you can use it !
Thinks !


对，你说的没错！
在版本v1.6.3之后，这个bug已经被修复 ，你可以使用最新版本。
谢谢 !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"熵增"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 中午11:08
收件人:&nbsp;"Cherry-toto/jizhicms"<jizhicms@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Cherry-toto/jizhicms] XSS  Stealing cookies (#16)





 
JIZHICMS 1.5.1 allows XSS to add an administrator cookie.
 
New normal account  =&gt;  New articles
 
 
code:
 <script&gt;alert(1)</script&gt;  

 
Go to administrator background
 

 
Click on the title to trigger XSS
